version: "3.8"

services:
  app:
    build: .
    container_name: iffiu-app
    env_file: .env
    networks:
      - default
      - kampa
    depends_on:
      - db
    volumes:
      - ./app:/app/app
    restart: unless-stopped

  sqs-worker:
    build: .
    container_name: iffiu-sqs-worker
    command: python -m app.services.sfn_poller
    env_file: .env
    networks:
      - default
      - kampa
    depends_on:
      - db
    volumes:
      - ./app:/app/app
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: iffiu-db
    environment:
      POSTGRES_DB: iffiu
      POSTGRES_USER: iffiu
      POSTGRES_PASSWORD: iffiu_secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: iffiu-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/iffiu-dashboard:/var/www/iffiu-dashboard:ro
      - /var/www/negotiatex:/var/www/negotiatex:ro
      - /var/www/certbot:/var/www/certbot:ro
    networks:
      - default
      - kampa
    depends_on:
      - app
    restart: unless-stopped

volumes:
  pgdata:

networks:
  default:
    name: iffiu-default
  kampa:
    external: true
    name: iffiu-network
